version: '2'
services:
  php:
    image: yiisoftware/yii2-php:8.2-apache
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app:delegated
    ports:
      - '8000:80'
    environment:
      - DATABASE_URL=sqlite:///app.db  # Configure to use SQLite

  adminer:
    image: adminer
    ports:
      - "8080:8080"
    environment:
      ADMINER_DEFAULT_DB_DRIVER: sqlite
#  db:
#    image: mysql:8
#    ports:
#      - "3307:3306"
#    volumes:
#      - mysql-data:/var/lib/mysql
#      - ./docker/mysql-config.cnf:/etc/mysql/conf.d/config.cnf
#    environment:
#      MYSQL_ROOT_PASSWORD: root
#      MYSQL_DATABASE: php_mvc
#      MYSQL_USER: php_mvc
#      MYSQL_PASSWORD: php_mvc
#  phpmyadmin:
#    image: phpmyadmin/phpmyadmin
#    ports:
#      - "8181:80"
#    environment:
#      PMA_HOST: db
#      PMA_PORT: 3306
#      MYSQL_ROOT_PASSWORD: root
#      MYSQL_USER: php_mvc
#      MYSQL_PASSWORD: php_mvc
#volumes:
#  mysql-data:
